version: '3.5'
services:
  pet-clinic:
    container_name: pet-clinic
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8085:8080
    environment:
      - SERVER_PORT=8080
    restart: always